### ISSUE TITLE
Getting error running dub build

### ISSUE THREAD

**Issue by midsubspace** [CyberShadow/steamguides#1]
![image](https://github.com/user-attachments/assets/2235c59f-7f3c-41ce-bdcd-223b715001c6)

**Comment by midsubspace** [comment]
Seems i needed to first run dub add ae in the project folder
![image](https://github.com/user-attachments/assets/1c91e146-d549-47ca-9fbf-067c476d7367)

**Comment by CyberShadow** [comment]
Thanks, fixed in c2b2e6a1f62ee1fb0a39afc89b079f9626adfdce.
